[metadata]
name = "ASE"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "s"
rarity = 9

[matches.allseeingeye]
regex = '^EYE1.(.*?)(\x02\d|\x03\d{2}|\x04\d{3}|\x05\d{4}|\x06\d{5})'
regex_flags = "s"
soft = false
product_name = "All-Seeing Eye"
info = "game: $1; port: $P(2)"
