[metadata]
name = "CIFS_NS_UC"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "\u0001\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\u0000\u0000 CKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\u0000\u0000!\u0000\u0001"
rarity = 8

[matches]
