[metadata]
name = "DNSStatusRequestTCP"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = "\u0000\f\u0000\u0000\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
rarity = 7

[matches.login]
regex = '''^\0\r\n\nLantronix ETS16 Version V([\d.]+)/\d+\(\d+\)\n\r\nType HELP at the 'BRTR-ETS16>' prompt for assistance\.\n\r\nUsername> '''
soft = false
product_name = "Lantronix ETS16 logind"
version = "$1"
device_type = "terminal server"

[matches.minecraft]
regex = '^[\xb0-\xdb]\x03[\x17-\x1a][\xad-\xd8]\x03\{"translate":"disconnect\.genericReason","with":\["Internal Exception: io\.netty\.handler\.codec\.DecoderException: us\.myles\.ViaVersion\.exception\.InformativeException: Please'
soft = false
product_name = "Minecraft game server"
info = "ViaVersion plugin"

[matches.wow]
regex = '^\0\0\t.{32}\x01.*?\0\x10..\0\0\0\0......([^\0]+)\x00([\d.]{7,15}:\d+)\0'
soft = false
product_name = "World of Warcraft authserver"
info = "realm: $1 on $2"

[matches.arcserve]
regex = '^([\w\d_-]+)\0$'
soft = false
product_name = "ARCserve Discovery"
hostname = "$1"

[matches.shell]
regex = '^\0rsh: \x10: Command not supported\n'
soft = false
product_name = "Ricoh rshd"
device_type = "printer"
