[metadata]
name = "GPRS_GTPv1"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "2\u0001\u0000\u0004\u0000\u0000B\u0000\u00137\u0000\u0000"
rarity = 9

[matches]
