[metadata]
name = "GPRS_GTPv2prime"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "N\u0001\u0000\u0004ÞþÈ\u0000"
rarity = 8

[matches]
