[metadata]
name = "iperf3"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = "0000000000000000000000000000000000000\u0000\u0000\u0000\u0000"
rarity = 9

[matches.iperf3]
regex = '^\t$'
soft = false
