[metadata]
name = "LibreOfficeImpressSCPair"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = """
LO_SERVER_CLIENT_PAIR
Nmap
0000

"""
rarity = 9

[matches.impress-remote]
regex = '^LO_SERVER_VALIDATING_PIN\n$'
soft = false
product_name = "LibreOffice Impress remote"
