[metadata]
name = "metasploit-xmlrpc"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = """
<?xml version=\"1.0\" ?><methodCall><methodName>nmap.probe</methodName></methodCall>
\u0000"""
rarity = 9

[matches.metasploit-xmlrpc]
regex = '<\?xml\x20version=\"1\.0\"\x20\?><methodResponse><fault><value><struct><member><name>faultCode</name><value><i4>-99</i4></value></member><member><name>faultString</name><value><string>Method\x20nmap\.probe\x20missing\x20or\x20wrong\x20number\x20of\x20parameters!</string></value></member></struct></value></fault></methodResponse>\n\0'
soft = false

[matches.omp]
regex = '^<omp_response status=\"400\" status_text=\"First command must be AUTHENTICATE, COMMANDS or GET_VERSION\"/>'
soft = false
product_name = "OpenVAS Management Protocol"
