[metadata]
name = "minecraft-ping"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = "þ\u0001"
rarity = 8

[matches.minecraft]
regex = '^\xff\x00.\x00\xa7\x00\x31\x00\x00(.+?)\x00\x00(.+?)\x00\x00(.+?)\x00\x00(.+?)\x00\x00(.+)'
regex_flags = "s"
soft = false
product_name = "Minecraft"
version = "$P(2)"

[matches.minecraft-classic]
regex = '^\x01\x01\x0eUnhandled message id "254"! {37}'
soft = false
product_name = "MCGalaxy Minecraft server"
