[metadata]
name = "NAT_PMP_ADDR"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "\u0000\u0000"
rarity = 8

[matches]
