[metadata]
name = "NessusTPv11"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = """
< NTP/1.1 >
"""
rarity = 9

[matches.nessus]
regex = '^< NTP/1.1 >\n'
soft = false
product_name = "Nessus Daemon"
info = "NTP v1.1"
