[metadata]
name = "OpenVPN"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "8dÁx\u0001¸Ë\u0000\u0000\u0000\u0000\u0000"
rarity = 8

[matches.openvpn]
regex = '^@........\x01\0\0\0\0d\xc1x\x01\xb8\x9b\xcb\x8f\0\0\0\0'
regex_flags = "s"
soft = false
product_name = "OpenVPN"

[matches.isakmp]
regex = '^................\x0b\x10\x05\0\0\0\0\0\0\0\0\(\0\0\0\x0c\0\0\0\x01\x01\0\0\x05'
soft = true
