[metadata]
name = "OPENVPN_PKI"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "8\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\u0000\u0000\u0000\u0000"
rarity = 9

[matches]
