[metadata]
name = "pc-anywhere"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "NQ"
rarity = 8

[matches.pc-anywhere]
regex = '^NR([^_]*)_*AHM_3___\0$'
regex_flags = "s"
soft = false
product_name = "Symantec pcAnywhere"
info = "Servername: $1"
