[metadata]
name = "Socks5"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = """
\u0005\u0004\u0000\u0001\u0002\u0005\u0001\u0000\u0003
google.com\u0000PGET / HTTP/1.0\r
\r
"""
rarity = 8
ports = [
    6660,
    6661,
    6662,
    6663,
    6664,
    6665,
    6666,
    6667,
    6668,
]

[matches.socks5]
regex = '^\x05'
soft = true

[matches.caldav]
regex = '^HTTP/1\.1 503 Service Unavailable\r\nServer: DavMail Gateway ([\w._-]+)\r\nDAV: 1, calendar-access, calendar-schedule, calendarserver-private-events, addressbook\r\n(?:[^\r\n]+\r\n)*?Content-Length: 83\r\n\r\nInvalid header: google\.com\0PGET / HTTP/1\.0, HTTPS connection to an HTTP listener \? '
regex_flags = "s"
soft = false
product_name = "DavMail CalDAV http gateway"
version = "$1"
device_type = "proxy server"

[matches.http]
regex = '^\x05\x04\0\x01\x02\x80\x05\x01\0\x03\ngoogle\.com\0PGET / HTTP/1\.0\r\n\r\n\0HTTP/1\.0 500 Internal Server Error\r\nContent-Length: 0\r\n\r\n'
soft = false
product_name = "DeviceWISE Enterprise M2M httpd"

[matches.fcp]
regex = '^ProtocolError\nFatal=true\nCodeDescription=ClientHello must be first message\nCode=1\nEndMessage\n$'
soft = false
product_name = "Freenet Client Protocol 2.0"

[matches.http-proxy]
regex = '^<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2\.0//EN\">\n<HTML><HEAD><TITLE>Error</TITLE></HEAD>\n<BODY><h2>400 Can not find method and URI in request</h2>\r\nWhen trying to load <a href=\"smartcache://url-parse-error\">smartcache://url-parse-error</a>\.\n<hr noshade size=1>\r\nGenerated by smart\.cache \(<a href=\"http://scache\.sourceforge\.net/\">Smart Cache ([\w._-]+)</a>\)\r\n</BODY></HTML>\r\n$'
soft = false
product_name = "Smart Cache http-proxy"
version = "$1"
