[metadata]
name = "STEAM"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "每每每每TSourceEngineQuery\u0000"
rarity = 8
ports = [
    27015,
    27016,
    27017,
    27018,
    27019,
    27020,
    27021,
    27022,
    27023,
    27024,
    27025,
    27026,
    27027,
    27028,
    27029,
]

[matches]
