[metadata]
name = "TS3INIT1"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = """
TS3INIT1\u0000e\u0000\u0000
9{\u000F\u0000[UrïÜx2k\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000"""
rarity = 9

[matches]
