[metadata]
name = "UbiquitiDiscoveryv2"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = "\u0002\b\u0000\u0000"
rarity = 9

[matches.ubiquiti-discovery]
regex = '^\x02[\x06\x09\x0b].[^\0].{48}'
regex_flags = "s"
soft = true
product_name = "Ubiquiti Discovery Service"
info = "v2 protocol"
