[metadata]
name = "UPNP_MSEARCH"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = """
M-SEARCH * HTTP/1.1\r
Host: 239.255.255.250:1900\r
Man: \"ssdp:discover\"\r
MX: 5\r
ST: ssdp:all\r
\r
"""
rarity = 8

[matches]
