[metadata]
name = "Ventrilo"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "udp"
request = """
\u0001çåu1£\u0017\u000B!Ï¿+NÝ\u0019¬Þ\b_$
\u0011\u0019¶so­(\u0013Ò
¹\u0012u"""
rarity = 9

[matches.ventrilo]
regex = "^.{111}"
regex_flags = "s"
soft = false
product_name = "Ventrilo"
version = "2.1.2+"
