[metadata]
name = "VerifierAdvanced"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = """
Query
"""
rarity = 8

[matches.crossmatchverifier]
regex = '^Settings\r\nGain\x20(\d+)\r\nContrast\x20(\d+)\r\nTime\x20(\d+)\r\nIllumination\x20(\d+)\r\nProcessed\r\n$'
soft = false
product_name = "Cross Match Verifier E fingerprint advanced control"
info = "Gain: $1; Contrast: $2; Time: $3; Illumination: $4"
