[metadata]
name = "vp3"
description = "TODO: Add description"
version = "0.1.0"
author = "Belousov Dmitry <me@beldmian.ru>"

[probe]
protocol = "tcp"
request = "vp3"
rarity = 8

[matches.vp3]
regex = "^ok$"
soft = false
product_name = "Voldemort"
